### ISSUE TITLE
Specific country search problem

### ISSUE THREAD

**Issue by naolarega** [Mikearaya/covid-telegram-bot#5]
I am unable to get a result for a specific country, only global statistics work.
![Screenshot_2020-08-14-11-09-28](https://user-images.githubusercontent.com/45383986/90228925-bcbbd400-de1f-11ea-9968-6a10db81de7b.png)

**Comment by Mikearaya** [comment]
@naolArega  thank you for taking it for a spin and reporting this issue :bowing_man: . I've fixed this issue so I'll be closing it for now. other suggestions or feature request is always welcome.

Stay Safe :safety_vest: :mask:
